### ISSUE TITLE
Doesn't delete completed tasks!

### ISSUE THREAD

**Issue by mbnoimi** [kewisch/gdata-provider#157]
### Describe the problem and steps to reproduce it:

I set many tasks as completed using [Google Tasks](https://play.google.com/store/apps/details?id=com.google.android.apps.tasks) app but Provider for Google Calendar doesn't sync Complete Status of these tasks!

### What did you expect to happen?

Sync task's Complete Status

### Anything else we should know?
It seems this bug [occurs since a while](https://groups.google.com/g/provider-for-google-calendar/c/qYVfncvbn-k/m/k_fSIFfWAAAJ).

**Comment by javierguzman** [comment]
I have had this error for a while as well.

**Comment by roberterzen** [comment]
I too have this problem.
I have Mozilla Thunderbird 78.10.1 (64 bit) and Provider for Google calendar version 78.0.1.
At first when I added my Calendar and Tasks from Google everything seemed right and fine. Then two anomalies popped up. 
First is as @mbnoimi described: When I mark task done in Google Tasks it remains undone in Thunderbird.
The second is even more annoying: When I add a task in Thunderbird New task window by clicking "Save and Close" it doesn't add the task and freezes. Only Thunderbird reset helps.
Is anyone working on this yet?
Thanks.

**Comment by tugkanbatu** [comment]
For your second problem:
Have you tried changing "Default Reminder" to something else, like "No Reminder"? That solves the problem ("create task" window not closing) for me.

**Comment by imacellone** [comment]
I'm having the same issues.

**Comment by carterbrandon** [comment]
I'm also finding that marking Tasks as completed, or deleting them, from the Android Calendar or Tasks app is not reflected in TB after syncing. Yet if I then try to complete or delete them in TB, there's a popup that they have been changed on the server, so it has registered *something*. Other edits in Android, like adding details or changing dates, go through OK.

W10, TB 78.11, Provider 78.01

**Comment by kewisch** [comment]
This is likely resolved with Thunderbird 91. Please reopen if not.

**Comment by Elijahh177** [comment]
For me, this problem still exists with Thunderbird 91.1.2 (64-bit).

**Comment by Hativ** [comment]
This problem still exists for me, too. Please reopen @kewisch 

gdata-provider 91.0.2
Thunderbird 91.4.1

**Comment by cdruee** [comment]
Problem persists in Thunderbird 102.4.2
