### ISSUE TITLE
URL links present in calendar entries in Google disappear in Thunderbird

### ISSUE THREAD

**Issue by ericzolf** [kewisch/gdata-provider#237]
### Describe the problem and steps to reproduce it:

URL links present in calendar entries in Google disappear in Thunderbird

Directly in Google Calendar:

![image](https://user-images.githubusercontent.com/3105685/133781771-c3e2c9f8-f590-4ca1-89e5-bba90c51712f.png)

In Thunderbird:

![image](https://user-images.githubusercontent.com/3105685/133781990-94f50c2b-3ace-4c06-81db-cb7cee5566d9.png)

### What happened?

The links disappear. I noticed once that an old invitation opened for the first time still contains the links for a very short time and it disappears to never reappear again.

### What did you expect to happen?

The links remain and are visible or even clickable in Thunderbird.

### Anything else we should know?

The issue appeared with the following upgrade, it wasn't there before:
    Upgrade       thunderbird-91.1.0-1.fc34.x86_64                            @updates
    Upgraded      thunderbird-78.11.0-1.fc34.x86_64                           @@System
    Upgrade       thunderbird-librnp-rnp-91.1.0-1.fc34.x86_64                 @updates
    Upgraded      thunderbird-librnp-rnp-78.11.0-1.fc34.x86_64                @@System

**Comment by ericzolf** [comment]
e-mails seem to survive the sync but else all https links are gone in Thunderbird.

**Comment by kewisch** [comment]
Ugh yes I know why. This was a change in Thunderbird that should have been handled a bit differently. I can probably fix this in the provider, but possibly not without having users do a full sync.

**Comment by kewisch** [comment]
Fixed in 6625aba20513a6f579261789ae8929e086328637

**Comment by ericzolf** [comment]
I have 91.0.2 and I still don't get the URL as such, also for new appointments. What did you mean exactly with a full sync?

Few more explanations:
* Bare URLs are fine, it's URLs with a description, where only the description remains, e.g. `<a href="https://example.com">my nice url</a>` becomes `my nice url`.
* The invitation e-mail itself looks good, e.g.: 
![image](https://user-images.githubusercontent.com/3105685/142203852-4c25fc82-8b98-4190-ae35-7a536c725497.png)
but once in the calendar: 
![image](https://user-images.githubusercontent.com/3105685/142203986-6d6f723b-66f2-44ac-9d0e-9451669c22f4.png)
(I don't mind losing the formatting, but the URL is an issue, and a regression)
