### ISSUE TITLE
Per event coloring from Google Calendar is lost on notification. (Bugzilla Bug 1288098)

### ISSUE THREAD

**Issue by kewisch** [kewisch/gdata-provider#6]
# [Bugzilla Bug 1288098](https://bugzilla.mozilla.org/show_bug.cgi?id=1288098)
Date: 2016-07-20T16:14:35+02:00
From: nnv@case.edu
Assigned To:   nobody

Last updated: 2019-05-01T12:23:02+02:00

**Comment by kewisch** [comment]
This should be fixed on the main branch

**Comment by zapper** [comment]
Thunderbird: Version 91.1.0 (64-Bit)
Provider for Google Calendar: Version 91.0.1

The issue seems still not to be fixed in above mentioned version. I tried also to remove the google calendar and added it back again - this also did not help.

From Debugging Console i can see that my Calendar Entry has: "colorId": "9" which should be shown as Blue in my Calendar.
My default calendar color is different (purple, i think that should be colorId 3).

Once i click the confirm button of the notification for the calendar entry it is updated and changes to the default color of my Calendar. I also can see that the colorId is not reflected in the put request (there is no colorId shown at all in the debug output at this time).

Will you re-open the issue or should a new one be entered? I am already waiting for quite long time for this issue to be solved since i am using the colors a lot to distinguish between my personal and buiness appointments.

**Comment by kewisch** [comment]
The main branch isn't yet released. Work in progress see #224 . However, I did add a workaround for 91.0.2 which will be released soon
