### ISSUE TITLE
Support for adding conference information at event creation

### ISSUE THREAD

**Issue by MSBlueVn** [kewisch/gdata-provider#664]
### Describe the problem and steps to reproduce it:

Get a meeting invite to your Google Workspace email in TB, accept it from that bar on top of the email, see if the meet link is saved.

### What happened?
When accepting a meeting from the email part of TB, the event is saved to the calendar, but the meeting link to google meet is removed from the event.

### What did you expect to happen?
When I accept a meeting from TB, the event would be saved correctly to the calendar.
Meeting link would be saved correctly.

**Comment by kewisch** [comment]
Meeting link support is read-only at the moment, I added a quick patch to at least show it recently. Unfortunately also the information that comes in doesn't provide a lot of info, I see a `X-GOOGLE-CONFERENCE` with the meet id. What I'd recommend is to go to your Google Calendar settings and enable the setting to automatically add invitations

**Comment by MSBlueVn** [comment]
The thing is, it also removes the meeting info from Google, so if I accept the invite and go to calendar I see no meet link.
Is there a way to maybe use an API call in this event to accept or decline in the server directly? That way you avoid being reliant on the info that comes from Google and the buttons are just API calls in disguise.

**Comment by kewisch** [comment]
Ah ok, so this also happens in the event dialog when you make a change there?

(not sure why I closed this btw, apologies)

**Comment by MSBlueVn** [comment]
I don't know which even dialog you are refering to, but I'll give you my full flow and tests so far:
1. I get an email invite in thunderbird
2. I click accept from the top of the preview of the email.
3. I go to calendar in thunderbird, there's no meet link there.
4. I go to Google Calendar on the web, it is also removed from there as well (but only for me, other people in that meeting still see that link on their event)
I hope this helps

**Comment by kewisch** [comment]
Try this flow (not advocating it is ideal, but to help identify the issue):

1. get email invite in Thunderbird
2. Go to calendar tab, refresh calendar
3. Find the event that you've been invited to
4. Double click to open, then edit
5. Change status to accepted, or make some other edit.

Alternatively, take some other even on your calendar you organized that has a conference info and edit it by changing something like the summary. Does the conf info retain?

**Comment by MSBlueVn** [comment]
2. I refreshed and synced nothing appeared, had to close and reopen thunderbird in order for it to show.
5. I do not see a way to change my attendance from the edit window, I looked in all tabs at the top, nothing regarding attendance.

I did the second thing you mentioned, edited the event from thunderbird, the meet was still there.

**Comment by kewisch** [comment]
Thanks. Then it would be great to see a difference in logs between these two actions. Note I think you can do right click on an event to change attendance.

I'm assuming one tries to create issues and then somehow overwrites the existing event, the other will simply take the existing event and edit it.

**Comment by MSBlueVn** [comment]
Strangely enough, right-clicking only works on the event I created, and not on events where I actually need to respond.
I think something there is reversed. I replied to my own event as attending, and when I right-click on an event I was invited to, the option to respond is not there.

In case it helps, accepting my own invitation via the right click did not remove the meet link.

**Comment by MSBlueVn** [comment]
Let me know if there are any logs I can share that will help figure this out.

**Comment by MSBlueVn** [comment]
Hey, how can we move this forward?

**Comment by kewisch** [comment]
I've fixed this in 9f2d19773211c91760d5cd4480c09396b72d183e for beta 139.9.3 which I will release soon

**Comment by MSBlueVn** [comment]
I am on 128.5.7 of the addon, and it still happened to me at least once.

**Comment by MSBlueVn** [comment]
Just installed the beta, now nothing works, see image:

<img width="1767" height="58" alt="Image" src="https://github.com/user-attachments/assets/fc3b4f1e-6035-484d-9cd5-9643ab9703c0" />
