### ISSUE TITLE
Birthdays Calendar

### ISSUE THREAD

**Issue by playful1510** [kewisch/gdata-provider#903]
Hi!
Running TB 128.8.1esr 64bit and provider 128.5.2. When I go to add my birthdays calendar from google, it doesn't appear in the list of available calendars. I had found 
> I ran into the issue that the new thunderbird 91 does not show all shared calenders. 
> 
> I then stumbled upon this [link](https://www.google.com/calendar/syncselect) where you can select which calender show up in thunderbird. 

 _Originally posted by @CheariX in [#194](https://github.com/kewisch/gdata-provider/issues/194#issuecomment-904732414)_

in an earlier thread, which let me add it through the normal TB 'On the Network' interface, but the events imported in this manner don't include some details that are available online, e.g. the actual birth date.

Is this a bug or just not implemented?

Thanks!

**Comment by rustycanb** [comment]
I think this might be a change in Google's API. On the Google Calendar web page, birthdays appear different to other calendars, with restricted options. I managed a rough hack by exporting my birthday calendar and importing that data into a new 'Birthdays+' calendar, which I could then connect to TB in the usual way. Of course, this hack will pick up changes in contacts' birthdays, as Google birthdays calendar does.

I am using the updated 128.5.2 version in TB128.8.0esr (64-bit). To attempt to isolate the issue, I reverted to gdata-provider 128.0 (which seemed to work flawlessly a few days ago) but Google birthdays calender is still not available to connect in TB using gdata-provider or Caldav (on the network option).

**Comment by Sp3EdeR** [comment]
I ran into the same now, even though I was subbed to Birthdays earlier. Feels like a regression, but I'm not certain.

**Comment by kewisch** [comment]
Because of an API change the birthdays are not provided anymore as a separate calendar, but these events are added to the regular calendar. I need to either add an option to display them on the main calendar, or provide a special birthdays calendar that just picks out birthday events from the main calendar.

**Comment by kewisch** [comment]
If you want to hack it in you'll need to change the eventTypes parameter to include birthdays in the source code

**Comment by rustycanb** [comment]
At this stage, I still have a separate Google Birthdays calendar with data from my Google Contacts. The separate calendar can be displayed in Thunderbird using a Caldav connection, but not using Gdata-Provider.

**Comment by kewisch** [comment]
Yeah, they might still have that via CalDAV, but they decided to go a different path with the API.

**Comment by rustycanb** [comment]
Thanks for the quick response.. I hope you are able to find a permanent solution because your add-on to TB is fantastic. Love it!!

**Comment by kewisch** [comment]
Fixed this in de883968a09b07d4b96f476c9fefda57040e5ef8 which will be part of 139.9.4. You can find the beta (currently at 139.9.3) at https://kewisch.github.io/gdata-provider/beta.html

**Comment by kewisch** [comment]
Note when the time comes you will need to specifically subscribe to the "Birthdays" variant of your primary calendar. I don't know if there are non-primary calendars that have birthday events, but I don't believe so.

**Comment by RobertL175** [comment]
Hi, thanks for your effort with fixing this issue. However, it still doesn't work on my side.
The "Birthdays" (German: Geburtstage) do not appear in the list when I try to add this calendar to Thunderbird from my Google calendars.
Version Thunderbird: 140.0
Version Provider für Google Kalender: 128.5.7

**Comment by Sp3EdeR** [comment]
> Hi, thanks for your effort with fixing this issue. However, it still doesn't work on my side. The "Birthdays" (German: Geburtstage) do not appear in the list when I try to add this calendar to Thunderbird from my Google calendars. Version Thunderbird: 140.0 Version Provider für Google Kalender: 128.5.7

@RobertL175 this fix has been added to provider v139.9, and is not part of the 128.5 version. If you want to test this, download the beta release: https://github.com/kewisch/gdata-provider/releases/tag/v139.9.3

**Comment by RobertL175** [comment]
@Sp3EdeR thanks for the quick response. Sorry, I thougt v139.9.3 would refer to the Thunderbird version. So I will wait for the release (I don't know how to download and run the beta version).
Thanks again (will also send a donation to appreciate all your activities regarding this great add-on).

**Comment by kewisch** [comment]
You can install the beta from here as well: https://kewisch.github.io/gdata-provider/beta.html
Basically just download it and then install from file in Thunderbird's add-on manager.
I can't promise when I'll release the provider beta, there are a bunch of little things I think I should take care of before a proper release.

**Comment by LarsErikOsterud** [comment]
I still have trouble getting birthdays in the calendar of my new Thunderbird installation.
On the Google side birthdays are set to be added to the main caladar.
But still does not show up in Thunderbird neither as a "Birthday" calendar not in the main Google calendar.
I also sync the Google adress book. But virthdays from there are not displayed either :-(
